VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "boxomatic/alpine-3.22"

	config.ssh.forward_agent = true
	config.ssh.insert_key = false

    config.vm.synced_folder "./confs", "/vagrant_data", create: true
    config.vm.synced_folder "./html", "/vagrant_html"

	config.vm.define "njegatS" do |njegatS_config|
		njegatS_config.vm.hostname = "njegatS"
		njegatS_config.vm.network :private_network, ip: "192.168.56.110"

		njegatS_config.vm.provider :virtualbox do |vb|
			vb.gui = false

			vb.memory = "2048"
			vb.cpus = "3"
		end

		njegatS_config.vm.provision "shell", path: "./scripts/server.sh"
	end
end